### ISSUE TITLE
Rename to generic fluent-plugin-out_tcp_secure?

### ISSUE THREAD

**Issue by LorenKeagle** [loomltd/fluent-plugin-loomsystems#3]
This plugin seems very useful for my needs (forwarding JSON events directly into a raw TCP listener), however I do not see any Loom Systems specific functionality in here.  I'm hesitant to integrate it into my solution because I believe it will cause confusion that we're trying to integrate with a 3rd party that we have no actual dependency on.

Don't get me wrong, I think it's a shame that basic transports are not covered under the base fluentd plugins, and I appreciate that you put in the time to develop this, but it seems like it would be adopted and used more if it didn't feel like an advertisement for Loom.

**Comment by doron327** [comment]
Hi. thanks for your feedback. 
This plugin was developed as part of my job and was developed for our customers to use. 
We decided to share it as an open-source so others can overcome this annoying limitation. 

As you mentioned there is no loomsystems specific code and you can use it for any purpose.
I agree with your feedback and I will change the name and I'll edit the description to point out the generic of this plugin. 

I hope changing the name won't affect the dependencies... :/ 
Thanks!
